name: tateworld
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  go_router: ^14.3.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  pocketbase: ^0.18.1
  image_picker: ^0.8.4+3
  provider: ^6.0.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  permission_handler: ^11.3.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  
